### ISSUE TITLE
Update 10x adapter wdls to run backup pipeline

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#246]
In an effort to 1) make sure Optimus can get into production as quickly as possible when ready and 2) de-risk the November launch in case Optimus gets delayed, we have decided to enabling the green box to run a simple 10x wrapped pipeline. This will serve as a test of the plumbing of the DCP to handle 10x data because it will be incorporated into the dcp wide integration test.

We'd like to be able to reuse as much of the 10x adapter wdls and subscription work when we do pick up Optimus into green box. If possible! 

Reminder that 10x cellranger expects files to be named a certain way, and we should have code already in the adapter wdls to do this.

AC:
10x adapter wdls can run the cellranger wrapped wdl pipeline

**Comment by samanehsan** [comment]
@dshiga and I were discussing offline that this ticket requires https://app.zenhub.com/workspace/o/humancellatlas/secondary-analysis/issues/96, but that is blocked by this ticket to fix/update the Optimus adapter WDL: https://app.zenhub.com/workspace/o/humancellatlas/secondary-analysis/issues/210 
 
@kbergin is it okay to move 96 & 210 to the top of the backlog? Also, I think we can combine them into one ticket, since the changes need to be tested together!
