### ISSUE TITLE
Sept 2018 F2F work

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#300]
At the F2F we made a bunch of PRs, this tracks that work and effort.

**Comment by rexwangcc** [comment]
A list of things we have done during the Eng F2F Meeting:
- Fixed an issue caused by too long service account name. (Lira PR #103)
- Fixed an issue which causes incorrect TLS certifications to be generated. (Lira PR #104)
- Updated the version endpoint of Lira to include `submit_and_hold` and `cache_wdls` info. (Lira PR #105)
- Fixed an issue which causes incorrect Lira config file to be rendered. (Lira PR #106)
- Updated the retry policy so we retry on 409 code when submitting to Ingest. (Pipeline-tools PR #78)
- Added maxRetries to submit WDL tasks. (Pipeline-tools PR #80)
- Updated the version of HCA CLI we use in submit WDL. (Pipeline-tools PR #81)
- Boosted the memory we use in specific tasks of SmartSeq2 pipeline (in branch `ds-boost-ss2-memory ` in skylab)
- Updated the bundle used in Mintegration test, and all of the changes @rhiananthony made to update to the new GKE cluster (Secondary-analysis PR #266 , #280 , #297 , #298 )
- Fixed an issue about docker port number conflicts in Mintegration test which breaks Mintegration tests if more than 2 running in the same time. (Secondary-analysis PR #299 )
- Updated to the new Lira GKE cluster with namespaces, for all of `dev`, `integration(test)` and `staging`.
- Created 3 new automated Jenkins Jobs for deploying Lira.
- Brought up the new GCP project with *ID* `broad-dsde-mint-integration`** and make it running in the dark.
- Fixed the production docker images in Job Manager and cut off a new release `v0.3.0` for JMUI, deployed this latest version of JMUI to caas-prod project. (Job Manager PR #467)
- Pushed the docker images used by pipeline-tools, `cromwell-metadata:v1.0.0` to all of dev, integration and staging envs' GCR, including caas-prod keys within them.
- Created new firecloud groups and added a set of DCP engineers to the group so they have access to Job Manager on CaaS prod now.
