### ISSUE TITLE
Update SS2 in Production

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#351]
After #347 the smartseq2 pipeline will have a new output format and a new version. These outputs are required for the matrix service to be able to work on HCA data.

AC:
New version of SS2 is running in integration (and thus will be promoted)
Tests pass

**Comment by rexwangcc** [comment]
@kbergin 
Comment on this ticket to track what we have done in order to merge the zarr output and group QC output:
- [ ] [pipeline-tools: Update the file format output for zarr matrix](https://github.com/HumanCellAtlas/pipeline-tools/pull/88)
- [x] [pipeline-tools: Update SS2 Adapter WDL to include zarr outputs](https://github.com/HumanCellAtlas/pipeline-tools/pull/87)
- [x] [pipeline-tools: Add web_summary.html to CellRanger adapter outputs](https://github.com/HumanCellAtlas/pipeline-tools/pull/86)
- [x] Tag pipeline-tools with `v0.33.0`
- [x] [Lira: Update the deploy script of Lira](https://github.com/HumanCellAtlas/lira/pull/110)
- [x] [Lira: Update default 10x wdl config in Lira's config](https://github.com/HumanCellAtlas/lira/pull/109)
- [x] [Lira: Improve the SS2 subscription query](https://github.com/HumanCellAtlas/lira/pull/108)
- [x] Tag Lira with `v0.14.0`
- [x] [secondary-analysis: Udpate the Mintegration test-suite to support Zarr outputs in SS2.](https://github.com/HumanCellAtlas/secondary-analysis/pull/359)
- [x] [sctools: Add unit tests for group qc functions](https://github.com/HumanCellAtlas/sctools/pull/48)
- [x] [sctools: Jx ss2 group qc](https://github.com/HumanCellAtlas/sctools/pull/47)
- [x] Tag sctools with `v0.3.0`
- [x] [skylab: Use sctools version in group qc wdl](https://github.com/HumanCellAtlas/skylab/pull/136)
- [x] [skylab: Add web_summary.html cellranger output](https://github.com/HumanCellAtlas/skylab/pull/135)
- [x] [skylab: Fix disk space issue for hisat2](https://github.com/HumanCellAtlas/skylab/pull/134)
- [x] [skylab: Kmk zarr conversion scripts](https://github.com/HumanCellAtlas/skylab/pull/133)
- [x] Tag Skylab with `smartseq2_v2.0.0`
- [x] Tag Skylab with `cellranger_v1.0.0`
- [x] Make new 10x and new ss2 subscriptions in integration DSS
- [x] Redeploy Lira to include the above changes.
