### ISSUE TITLE
Multiplexed (pooled) 10xV2 data

### ISSUE THREAD

**Issue by samanehsan** [HumanCellAtlas/secondary-analysis#396]
The 10X dataset `rsatija` (Multiplexed scRNA-seq with barcoded antibodies) for the closed beta has samples from 8 donors that were combined and then sequenced to produce an R1 and R2 fastq file. In the bundle `8ebd32c8-d172-40c1-8293-17413f8922d4` links.json this is represented as: 
```    
                {
                  "input_type": "biomaterial",
                  "inputs": [
                    "7f8ea693-0754-4071-9df4-41495497ba33",
                    "b4de018a-c4b7-40bb-ba8e-cfb02c84eb36",
                    "b38e733e-683a-428c-9b4b-4a4e031817cc",
                    "fae30d4c-eb31-4454-9be8-783d8716f0cb",
                    "944c41fe-fc8c-45cf-9675-cd924aa7beb8",
                    "5bcae630-6241-4288-ab9d-155078a97d73",
                    "f6c2b536-7ac0-4ee5-9693-1bdc5c35ea44",
                    "78d2aaeb-b7db-4f4d-8e82-9c6e9f36d33d"
                  ],
                  "output_type": "file",
                  "outputs": [
                    "87bd6a33-805b-473f-a96b-3b4b738e7d7e",
                    "2ab39475-5b93-47e9-a0b9-b13b608d2de2"
                  ],
                  "process": "55fb408e-16e2-4c42-abe1-c8aa495bae1f",
                  "protocols": [
                    {
                      "protocol_id": "97f58c55-82cd-450e-9caf-a79093b46507",
                      "protocol_type": "library_preparation_protocol"
                    },
                    {
                      "protocol_id": "d671e111-ae1b-42e9-99cb-9502e5b075d3",
                      "protocol_type": "sequencing_protocol"
                    }
                  ]
                }
```
This breaks our pipelines, which expect one "sample_id" (the file uuid of the biomaterial that is sequenced):
- https://github.com/HumanCellAtlas/pipeline-tools/blob/master/adapter_pipelines/ss2_single_sample/adapter.wdl#L113
- https://github.com/HumanCellAtlas/pipeline-tools/blob/master/adapter_pipelines/cellranger/adapter.wdl#L181 (The sample_id here is currently only used as the name of the outputs folder)

A related issue is that the CellRanger pipeline should be updated to handle the case where the fastq files from different lanes are from different samples.

ACs:
- Lira does not throw an error if multiple sample_ids are received in the additional metadata for the notification 
- Update pipeline-tools to use the "correct" sample id/sample name

**Comment by kbergin** [comment]
I spoke with @malloryfreeberg about this a bit more today. We think it makes the most sense for the wranglers to ask for only lane-demultiplexed data. In this case, if a sample was split across multiple lanes, we may get multiple fastqs to process together. But every fastq we get should only have one sample in it for our 10x and SS2 pipelines as they are now.

This isn't a blanket statement however, as for cell hashing I think we have to keep some of the samples multiplexed. This is ok because our current pipeline isn't meant to analyze that type of data anyways. 

In general, I think we need to revisit our queries for subscriptions in the new year. They likely need to be more specific. It's better for them to be too specific than too loose. We can always find more data to analyze retroactively, but producing bad or poor quality science is a much larger problem.

**Comment by samanehsan** [comment]
Thank you for the clarification! If we cannot currently process data that has multiple sample ids, the ACs no longer make sense, so I think we can close this issue in favor of #398. What do you think @kbergin?

**Comment by kbergin** [comment]
I think you're right. I think I will make that ticket a bit more generic re: revisiting our query as a whole.

**Comment by malloryfreeberg** [comment]
@kbergin @samanehsan everything here sounds good to me :)
