### ISSUE TITLE
Run PBMC test data through 10x and Optimus

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#454]
Run PBMC_4k dataset from 10X through 10x and Optimus

TODO:
- [x] Run  Cellranger V3 with GRCh38_V27 Gencode annotation (filtered as required by CR)
- [x] Run Optimus with GRCh38_V27 Gencode
- [x] Generate filtered reference for Optimus
- [ ] Run Optimus with GRCh38_V27 Gencode filtered

Notes:
 * Jishu already ran PBMC 4k through Cellranger with ensembl and gencode reference [here](https://drive.google.com/drive/u/0/folders/15xeKWsa7NOAQoWI8LnzA3p8AHai_-8Tt)
 * Marked as blocked because 10x we want to wait until we compare v2 and v3. We can continue to run Optimus in the mean time. 
 * Watch out for scope creep with Optimus / 10x bugs - make new tickets if we run into them.

ACs:
- [ ] Matrices are produced for Cellranger and Optimus (with and without filtering) [3 runs total]
- [ ] Outputs in public cloud location that is documented (including BAM files)
- [ ] Generate spreadsheet to track runs, including cromwell workflow ids as well as which reference and annotation pair and pipeline and dataset are used.

**Comment by barkasn** [comment]
Following up from the comparison of 10X V2 and V3 which was done with the same dataset, I am working on this. 

4k PBMC is running of nb-devbox for both V2 and V3, under the directory:
/home/nbarkas/storage2/nbarkas/cmpCellrangerVsOptimus_Gencode/cellranger

4k PBMC is also running with Optimus in our dev cromwell environment. In the course of this I have found some memory problems, that I have fixed. They are currently checked into github under skylab as nb-optimus-fixes, will PR once I have the pipeline working.

Also while doing this I found that the CountSparseMatrix step was failing because of an old scipy version in secondary-analysis-sctools:0.1.10. I've made a new release of sctools: secondary-analysis-sctools:v0.3.1 and that has been amended in the pipeline and this has also been checked in to the branch above.

**Comment by barkasn** [comment]
Update:

* Both V2 and V3 cellranger have been run (devbox:~/storage3/nbarkas/work/cmpCellrangerVsOptimus_Gencode/4k_pbmc)
* Optimus has run with the full annotation
(b9552265-d9b0-4fbe-94b8-a070885bcb77)
* Optimus (STAR) filtered annotation has run (/home/nbarkas/storage2/nbarkas/mkStarFiltered/scratch1)
* Optimus annotation is at gs://hca-dcp-mint-test-data/nb-cmpOptimus_Cellranger/GRCh38_Gencode_filtered/
