### ISSUE TITLE
Verify that corrected barcodes are used in Optimus

### ISSUE THREAD

**Issue by barkasn** [HumanCellAtlas/secondary-analysis#515]
Some steps towards the end of the pipeline _may not_ use the corrected barcodes.

AC:
- [ ] Verify that corrected barcodes (CB) are used through-out~and the pipeline falls back to raw barcodes (CR) when these are absent.~
- [ ] Check for if there is overlap with PR https://github.com/HumanCellAtlas/sctools/pull/56

**Comment by samanehsan** [comment]
Is there a way to write unit tests in sctools to verify this behavior, so that we do not have to manually verify it in the future?

**Comment by kishorikonwar** [comment]
We verified that the barcodes are correctly added to the bam file of reads in the Attach10XBarcodes step of the Optimus pipeline.  Currently, Optimus corrects the barcode from the sequencer (i.e. CR)  by correcting it up to an edit distance (by substitution) of 1 against the whitelist for Cellranger. 

I ran a test with a subset of the PBMC 4K data and computed the edit distances of each barcode and noted that only barcodes (added as CB) within an edit distance of 1 is used in the downstream analysis, otherwise, they are not added to the bam file. Note that for the barcodes that are not corrigible the CB tag is left empty which was the reason for the failure of the CalculateCellMetrics stop for the missing alignments.

**Comment by barkasn** [comment]
I would like clarify that we need to verify that the CB barcodes are used by all the steps one by one. I also noticed that you have crossed out the "fallback to CR barcodes". Why is that? All the code I have seen so far aim to fall back to CR. We should make sure this is done consistently.

**Comment by samanehsan** [comment]
Hi @ambrosejcarr! Can you please clarify what the intended behavior around CB barcodes is here? It sounds like there is confusion around whether or not the pipeline falls back to raw barcodes (CR) when the corrected cell barcodes are absent.

**Comment by ambrosejcarr** [comment]
Certainly. The intended behavior is drawn from the [SAM tags specification](http://samtools.github.io/hts-specs/SAMtags.pdf), which states: 
```
CB Z Cell identifier
CR Z Cellular barcode sequence bases (uncorrected)
```

A read is assigned a cell barcode tag (`CB`) if and only if it considered to represent a valid cell. This happens during cell barcode correction. Consequently, any read with a `CB` tag can be thought to be associated with a cell. 

However, we do not hard-filter reads (exclude them from our output files) so that users have them available if they wish. These "failing" reads can be very useful for technology development or QC. There are common problems where the sequencer will assign ambiguous bases which makes it hard to match cell barcodes, and having the failing reads handy is useful to debug these problems.

We also use them internal for metric calculations -- the number of reads that have `CR` but not `CB` equals the number of reads failing cell barcode correction, for example. 

I hope this gives enough background on the intent of the barcodes to interpret their use. `CR` should _probably_ only be used for metrics calculations, and `CB` reads should be used to construct the count matrix.
