### ISSUE TITLE
SPIKE: Investigate what needs to be done to place a beta metadata tag on a beta pipeline

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/secondary-analysis#791]
┆Issue is synchronized with this [Jira Story](https://broadinstitute.atlassian.net/browse/GH-496)

**Comment by kbergin** [comment]
@brianraymor This ticket is what is currently being worked on, I'll link it to the epic.

**Comment by brianraymor** [comment]
If a Spike is required to estimate the Epic, then the Spike would have its Release and Milestone (timebox) set and its Epic would not be set until the Spike is complete. Also - what's the success criteria / deliverable for the Spike?

**Comment by jkaneria** [comment]
@brianraymor Success Criteria for the spike would be to define what is required to implement a indicator on the data to let users know at what tier it belongs to in the greater DCP and to define technical mechanism for moving between the tiers. The closing of this spike will result in greater clarity for the other child tickets in https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/dcp/270. 

The closing of the spike should also give power to the POs on Data Browser and Azul to plan when they can execute the work required.

**Comment by brianraymor** [comment]
Please see [Modeling Objectives Requiring Further Research](https://github.com/HumanCellAtlas/dcp-community/blob/master/rfcs/text/0012-roadmaps%2Bplanning.md#modeling-objectives-requiring-further-research) for how the epic and spike should be modeled on the DCP board. For example, the spike should be a Release and a Milestone and a reference to the work-in-progress noted above. The epic cannot be scheduled accurately until the spike completes so it has no release or milestone. 

I'd also note that the matrix service might have related work since we expose:

  "field_description": "Whether the secondary analysis protocol has been reviewed and approved the HCA Analysis Working Group.",
  "field_name": "analysis_working_group_approval_status",

It's unclear because the objective speaks of "community" pipelines and the spike of "beta pipelines".

**Comment by brianraymor** [comment]
@jkaneria - Is [Tagging Analysis Pipelines](https://docs.google.com/document/d/1y5Wrt4sdarhodm997hcwntWGcV_SE3JIKzKHMdIG8pU/edit#heading=h.6ozxco8qg3wx) intended to be the Spike _work-in-progress_?

**Comment by kbergin** [comment]
➤ Saman Ehsan commented:

https://docs.google.com/document/d/1y5Wrt4sdarhodm997hcwntWGcV_SE3JIKzKHMdIG8pU/edit# ( https://docs.google.com/document/d/1y5Wrt4sdarhodm997hcwntWGcV_SE3JIKzKHMdIG8pU/edit#|smart-link )

**Comment by kbergin** [comment]
➤ Saman Ehsan commented:

The option to add the tag to the analysis metadata is blocked by AUDR analysis updates, so this SPIKE requires more discussion.

**Comment by kbergin** [comment]
➤ Saman Ehsan commented:

[~accountid:5b43ab1e441e440653b0a4d9] should this go into the backlog since this work has been de-prioritized?

**Comment by kbergin** [comment]
➤ Saman Ehsan commented:

Or we could move it to done since the work to SPIKE on this topic is complete and the conclusion was that the work is more complicated than it initially seemed and it is no longer a top priority.
